// This file is auto generated by icy-vector.
#ifndef TABLE_COMPILER_INDEX
#define TABLE_COMPILER_INDEX
#define array_element_size(array) sizeof(array[0])
#define array_count(array) (sizeof(array)/array_element_size(array))
#include "icydb.h"
#include <stdlib.h>
#endif

TABLE_NAME * TABLE_NAME_create(const char * optional_name){
  static const char * const column_names[] = COLUMN_NAMES;
  static const char * const column_types[] = COLUMN_TYPE_NAMES;

  TABLE_NAME * instance = calloc(sizeof(TABLE_NAME), 1);
  unsigned int sizes[] = COLUMN_SIZES;
  
  instance->column_names = (char **)column_names;
  instance->column_types = (char **)column_types;
  
  ((size_t *)&instance->column_count)[0] = COLUMN_COUNT;
  for(unsigned int i = 0; i < COLUMN_COUNT; i++)
    ((size_t *)instance->column_sizes)[i] = sizes[i];

  icy_vector_abs_init((icy_vector_abs * )instance, optional_name);

  return instance;
}


TABLE_NAME_index TABLE_NAME_alloc(TABLE_NAME * table){
  icy_index idx = icy_vector_abs_alloc((icy_vector_abs *) table);
  TABLE_NAME_index index;
  index.index = idx.index;
  return index;
}

TABLE_NAME_indexes TABLE_NAME_alloc_sequence(TABLE_NAME * table, size_t count){
  icy_indexes idx = icy_vector_abs_alloc_sequence((icy_vector_abs *) table, count);
  TABLE_NAME_indexes index;
  index.index = idx.index.index;
  index.count = count;
  return index;
}

void TABLE_NAME_remove(TABLE_NAME * table, TABLE_NAME_index index){
  icy_index idx = {.index = index.index};
  icy_vector_abs_remove((icy_vector_abs *) table, idx);
}

void TABLE_NAME_remove_sequence(TABLE_NAME * table, TABLE_NAME_indexes * indexes){
  icy_indexes idxs;
  idxs.index.index = (unsigned int)indexes->index;
  idxs.count = indexes->count;
  icy_vector_abs_remove_sequence((icy_vector_abs *) table, &idxs);
  memset(&indexes, 0, sizeof(indexes));
  
}
void TABLE_NAME_clear(TABLE_NAME * table){
  icy_vector_abs_clear((icy_vector_abs *) table);
}

void TABLE_NAME_optimize(TABLE_NAME * table){
  icy_vector_abs_optimize((icy_vector_abs *) table);
}
void TABLE_NAME_destroy(TABLE_NAME ** table){
  icy_vector_abs_destroy((icy_vector_abs **) table);
}
