// This file is auto generated by icy-vector
#include "icydb.h"
typedef struct _TABLE_NAME{
  char ** column_names;
  char ** column_types;
  size_t * count;
  size_t * capacity;
  size_t * free_index_count;
  const size_t column_count;
  icy_mem * free_indexes;
  icy_mem * header;
  const size_t column_sizes[COLUMN_COUNT];
  
  VALUE_COLUMNS1;
  MEM_AREAS;
}TABLE_NAME;

// a vector index.
typedef struct{
  size_t index;
}TABLE_NAME_index;

typedef struct{
  size_t index;
  size_t count;
}TABLE_NAME_indexes;

TABLE_NAME * TABLE_NAME_create(const char * optional_name);
TABLE_NAME_index TABLE_NAME_alloc(TABLE_NAME * table);
TABLE_NAME_indexes TABLE_NAME_alloc_sequence(TABLE_NAME * table, size_t count);
void TABLE_NAME_remove(TABLE_NAME * table, TABLE_NAME_index index);
void TABLE_NAME_remove_sequence(TABLE_NAME * table, TABLE_NAME_indexes * indexes);
void TABLE_NAME_clear(TABLE_NAME * table);
void TABLE_NAME_optimize(TABLE_NAME * table);
void TABLE_NAME_destroy(TABLE_NAME ** table);
