// This file is auto generated by table_compiler
#include "icydb.h"
typedef struct _int_set{
  char ** column_names;
  char ** column_types;
  size_t count;
  const bool is_multi_table;
  const int column_count;
  int (*cmp) (const int * k1, const int * k2);
  const size_t sizes[1];

  int * key;
  icy_mem * key_area;
}int_set;

int_set * int_set_create(const char * optional_name);
void int_set_set(int_set * table, int key);
void int_set_insert(int_set * table, int * key, size_t count);
void int_set_lookup(int_set * table, int * keys, size_t * out_indexes, size_t count);
void int_set_remove(int_set * table, int * keys, size_t key_count);
void int_set_clear(int_set * table);
void int_set_unset(int_set * table, int key);
bool int_set_try_get(int_set * table, int * key);
void int_set_print(int_set * table);
size_t int_set_iter(int_set * table, int * keys, size_t keycnt, int * optional_keys_out, size_t * indexes, size_t cnt, size_t * iterator);
